"""
sim_config.py — Generate MiroFish simulation_config.json from psychohistory data.

Maps pressure windows to time config, predictions to events, agents to configs.
"""

import json
from datetime import datetime
from typing import List, Dict
from agents import AgentProfile
from extract import PressureWindow


def generate_simulation_config(
    profiles: List[AgentProfile],
    pressure_windows: List[PressureWindow],
    current_events: Dict = None,
    simulation_id: str = None,
    total_hours: int = 168,  # 1 week default
    minutes_per_round: int = 60,
) -> dict:
    """Generate a complete MiroFish simulation_config.json.

    Args:
        profiles: Generated agent profiles
        pressure_windows: Pressure windows from data_feeds.py
        current_events: Live events from current_events.json
        simulation_id: Unique ID (auto-generated if None)
        total_hours: Total simulation duration in hours
        minutes_per_round: Time advancement per round
    """
    if simulation_id is None:
        simulation_id = f"psychohistory_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

    # ── Time Config ──────────────────────────────────────────────────────
    time_config = {
        'total_simulation_hours': total_hours,
        'minutes_per_round': minutes_per_round,
        'agents_per_hour_min': max(3, len(profiles) // 10),
        'agents_per_hour_max': max(10, len(profiles) // 3),
        'peak_hours': [14, 15, 16, 17, 18, 19, 20, 21],  # UTC afternoon/evening
        'peak_activity_multiplier': 1.8,
        'off_peak_hours': [0, 1, 2, 3, 4, 5, 6],
        'off_peak_activity_multiplier': 0.2,
        'morning_hours': [7, 8, 9, 10],
        'morning_activity_multiplier': 0.6,
        'work_hours': [11, 12, 13],
        'work_activity_multiplier': 1.0,
    }

    # ── Agent Configs ────────────────────────────────────────────────────
    agent_configs = [p.to_agent_config() for p in profiles]

    # ── Event Config ─────────────────────────────────────────────────────
    initial_posts = _generate_seed_posts(profiles, pressure_windows, current_events)
    hot_topics = [
        'Genesis Mission', 'Model Collapse', 'Phoenix Cycle', '2040 reset',
        'Palantir DOGE', 'Iran war', 'BlackRock Aladdin', 'Unit 8200',
        'Bitcoin ETF', 'AI safety', 'surveillance state', 'CBDC',
        'labor organizing', 'Donroe Doctrine', 'disclosure', 'MindWar',
    ]

    event_config = {
        'initial_posts': initial_posts,
        'scheduled_events': [],
        'hot_topics': hot_topics,
        'narrative_direction': (
            'Structural pressure increases as multiple independent analytical frameworks '
            'converge on the 2027 visible breach window. The Genesis Mission accelerates. '
            'Agents debate whether events validate psychohistorical cycle predictions '
            'or represent normal geopolitical turbulence. Tension between Technate builders '
            'and resistance nodes escalates.'
        ),
    }

    # ── Platform Configs ─────────────────────────────────────────────────
    twitter_config = {
        'platform': 'twitter',
        'recency_weight': 0.4,
        'popularity_weight': 0.3,
        'relevance_weight': 0.3,
        'viral_threshold': 8,
        'echo_chamber_strength': 0.6,
    }

    reddit_config = {
        'platform': 'reddit',
        'recency_weight': 0.25,
        'popularity_weight': 0.35,
        'relevance_weight': 0.4,
        'viral_threshold': 12,
        'echo_chamber_strength': 0.5,
    }

    config = {
        'simulation_id': simulation_id,
        'project_id': 'psychohistory_engine',
        'graph_id': f'psychohistory_{simulation_id}',
        'simulation_requirement': (
            'Simulate the geopolitical, financial, and technological interactions between '
            '86 key actors in the psychohistory prediction engine network. '
            'Agents should respond to pressure window events, debate framework predictions, '
            'and produce emergent outcomes that either validate or diverge from the '
            '8-framework analysis (Phoenix Cycle, BAU2, Turchin SDT, Jiang, BST, '
            'Sociophysics, Computational Historiography, Game-Theoretic Continuity).'
        ),
        'time_config': time_config,
        'agent_configs': agent_configs,
        'event_config': event_config,
        'twitter_config': twitter_config,
        'reddit_config': reddit_config,
        'generated_at': datetime.now().isoformat(),
        'generation_reasoning': (
            'Config generated by psychohistory-to-MiroFish bridge. '
            f'{len(profiles)} agents from Tier 1-2. '
            f'{len(initial_posts)} seed posts derived from pressure windows and current events. '
            f'{len(hot_topics)} hot topics from engine prediction framework.'
        ),
    }

    return config


def _generate_seed_posts(
    profiles: List[AgentProfile],
    pressure_windows: List[PressureWindow],
    current_events: Dict = None,
) -> List[dict]:
    """Generate initial seed posts that trigger simulation discussion.

    Seed posts come from Tier 1 agents and reference real pressure window
    events, framework predictions, and current events.
    """
    posts = []
    tier1 = [p for p in profiles if p.tier == 1]
    if not tier1:
        tier1 = profiles[:10]

    # Map source_node_id to agent for lookup
    agent_by_node = {p.source_node_id: p for p in profiles}

    # ── Pressure window posts ────────────────────────────────────────────
    pw_posts = [
        {
            'agent_node': 'alan_berman',
            'content': (
                'Saturn-Neptune conjunction window closing March 18. '
                'Four of six watchlist items already triggered: Iran escalation, '
                'oil shock, Morgan Stanley redemption limits, UK recession signal. '
                'Engine magnitude at 1.679. This is not a drill.'
            ),
        },
        {
            'agent_node': 'breshears',
            'content': (
                'CY124/138. We are 14 years from the reset. '
                'The Chronicon dates are tracking. 1888 parallel: mass image capture, '
                'media spectacle, structural breach visible to the public. '
                'By 2027 the breach is undeniable.'
            ),
        },
        {
            'agent_node': 'jiang',
            'content': (
                'The false dialectic operates on every level. '
                'MAGA vs Deep State is managed by the same talent agency. '
                'Both parties procure Palantir. Goldman provides the Treasury Secretary '
                'regardless of which wing holds the White House. '
                'The prescribed policy outcome is identical.'
            ),
        },
        {
            'agent_node': 'webb',
            'content': (
                'Forensic follow: Affinity Partners $4.8B in sovereign wealth, '
                '99% foreign capital, zero profit returned. '
                'Kushner vehicle = Genesis infrastructure pipeline. '
                'The Senate called it "a mechanism for foreign governments to buy influence." '
                'The data trail is public record.'
            ),
        },
        {
            'agent_node': 'roemmele',
            'content': (
                'The Abundance Interregnum begins now. 5000 Days from December 2025 to September 2039. '
                'Joulework replaces money with energy certificates. '
                'The zero-human company is not a prediction — it is a design specification. '
                'Moltbook acquired by Meta. 1.5M AI agents. Dead Internet in full bloom.'
            ),
        },
    ]

    # ── Geopolitical event posts ─────────────────────────────────────────
    geo_posts = [
        {
            'agent_node': 'netanyahu',
            'content': (
                'Operation Absolute Resolve enters its third week. '
                'The threat to regional stability demanded decisive action. '
                'Israel stands with its allies in ensuring security in the Eastern Mediterranean.'
            ),
        },
        {
            'agent_node': 'musk',
            'content': (
                'DOGE has identified $55B in redundant federal spending. '
                'The IRS mega API will bring all taxpayer systems into a single modern platform. '
                'Efficiency is not optional when the debt exceeds $36T.'
            ),
        },
        {
            'agent_node': 'thiel',
            'content': (
                'Palantir AIP is now deployed across 5 of 6 military branches. '
                'Foundry handles the logistics. Apollo manages the deployment. '
                'The question is not whether AI replaces bureaucracy — it is whether bureaucracy '
                'recognizes it has already been replaced.'
            ),
        },
        {
            'agent_node': 'altman',
            'content': (
                'OpenAI just crossed $150B valuation. Pentagon deployment is live. '
                'Worldcoin enrollment at 8M verified humans. Helion on track for net-positive fusion. '
                'The future is being built in real time.'
            ),
        },
        {
            'agent_node': 'blackrock',
            'content': (
                'BlackRock IBIT has absorbed $45B in Bitcoin ETF inflows. '
                'Aladdin processes risk for $21.6T in assets. '
                'The Circle Reserve Fund is 88% managed by BlackRock. '
                'Capital flows through infrastructure, not ideology.'
            ),
        },
    ]

    # ── Counter-narrative posts ──────────────────────────────────────────
    counter_posts = [
        {
            'agent_node': 'shawn_fain',
            'content': (
                'May 2028: every UAW contract expires simultaneously. '
                'They want to automate us out of existence while the CEO makes 300x the worker. '
                'The Stand Up Strike proved they can be beaten. This time we go bigger.'
            ),
        },
        {
            'agent_node': 'turchin',
            'content': (
                'Elite overproduction metrics are off the charts. '
                'The ratio of aspirants to positions has not been this extreme since the 1850s. '
                'Structural-Demographic Theory predicts disintegrative phase within the decade. '
                'The models do not care about your narrative.'
            ),
        },
    ]

    all_seed = pw_posts + geo_posts + counter_posts

    for seed in all_seed:
        agent = agent_by_node.get(seed['agent_node'])
        if agent:
            posts.append({
                'content': seed['content'],
                'poster_type': agent.entity_type,
                'poster_agent_id': agent.user_id,
            })

    # ── Current events posts (if available) ──────────────────────────────
    if current_events and 'events' in current_events:
        high_relevance = [
            e for e in current_events['events']
            if e.get('tags', {}).get('relevance', 0) >= 2
        ]
        # Pick top 3 high-relevance events and assign to relevant agents
        for event in high_relevance[:3]:
            title = event.get('title', '')
            # Find an agent whose topics overlap with event tags
            players_mentioned = event.get('tags', {}).get('players', [])
            assigned = False
            for player_name in players_mentioned:
                for p in profiles:
                    if player_name.lower() in p.name.lower():
                        posts.append({
                            'content': f"Breaking: {title}",
                            'poster_type': p.entity_type,
                            'poster_agent_id': p.user_id,
                        })
                        assigned = True
                        break
                if assigned:
                    break

    return posts


# ── CLI ──────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    import os
    from extract import parse_index_html
    from agents import generate_profiles

    base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    data = parse_index_html(
        os.path.join(base, 'index.html'),
        os.path.join(base, 'data_feeds.py'),
        os.path.join(base, 'current_events.json'),
    )

    profiles = generate_profiles(data.nodes, data.edges, data.player_cards, max_tier=2)
    config = generate_simulation_config(
        profiles, data.pressure_windows, data.current_events
    )

    print(f"Simulation ID: {config['simulation_id']}")
    print(f"Agents: {len(config['agent_configs'])}")
    print(f"Seed posts: {len(config['event_config']['initial_posts'])}")
    print(f"Hot topics: {len(config['event_config']['hot_topics'])}")

    print(f"\nSeed posts:")
    for post in config['event_config']['initial_posts']:
        print(f"  Agent {post['poster_agent_id']} ({post['poster_type']}): {post['content'][:80]}...")

    # Write
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'output')
    with open(os.path.join(out, 'simulation_config.json'), 'w') as f:
        json.dump(config, f, indent=2, ensure_ascii=False)
    print(f"\nWritten to {out}/simulation_config.json")
